const{axios,APS,cfg,basic,enc,session,cookie,token,user,account,payload,error}=require('../lib/_lib');
async function pages(url,t){let all=[],offset=0,total=1;while(offset<total){const join=url.includes('?')?'&':'?';const r=await axios.get(`${url}${join}limit=200&offset=${offset}`,{headers:{Authorization:`Bearer ${t}`}});const batch=r.data.results||[];all.push(...batch);total=r.data.pagination?.totalResults||all.length;offset+=r.data.pagination?.limit||200;if(!batch.length)break}return all}
async function companies(aid,t,status='all'){return pages(`${APS}/construction/admin/v1/accounts/${aid}/companies?filter%5Bstatus%5D=${encodeURIComponent(status)}&sort=name`,t)}
module.exports=async(req,res)=>{try{const a=String(req.query.action||'');
if(a==='auth-login'){cfg();const u=new URL(`${APS}/authentication/v2/authorize`);u.search=new URLSearchParams({response_type:'code',client_id:process.env.APS_CLIENT_ID,redirect_uri:process.env.APS_CALLBACK_URL,scope:'data:read account:read account:write'});return res.json({url:u.toString()})}
if(a==='auth-callback'){const b=new URLSearchParams({grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.APS_CALLBACK_URL}),r=await axios.post(`${APS}/authentication/v2/token`,b,{headers:{Authorization:`Basic ${basic()}`,'Content-Type':'application/x-www-form-urlencoded'}});cookie(res,enc({access_token:r.data.access_token,refresh_token:r.data.refresh_token}));return res.json({ok:true})}
if(a==='auth-logout'){res.setHeader('Set-Cookie','autodesk_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return res.json({authenticated:false})}
if(a==='auth-status')return res.json({authenticated:!!session(req)});
if(a==='hubs'){const t=await user(req),r=await axios.get(`${APS}/project/v1/hubs`,{headers:{Authorization:`Bearer ${t}`}});return res.json({hubs:(r.data.data||[]).map(h=>({id:h.id,name:h.attributes?.name||h.id,accountId:account(h.id)}))})}
if(a==='companies-existing'){const aid=account(req.query.hubId),t=await user(req),all=await companies(aid,t,'active');return res.json({companies:all.map(c=>({id:c.id,name:c.name,trade:c.trade,status:c.status}))})}
if(a==='companies-import-batch'){const aid=account(req.body.hubId),items=(req.body.companies||[]).map(payload).filter(Boolean).slice(0,50),t=await token('account:write'),r=await axios.post(`${APS}/hq/v1/accounts/${aid}/companies/import`,items,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}}),batchNumber=req.body.batchNumber;return res.json({batchNumber,totalBatches:req.body.totalBatches,addedCompanies:(r.data.success_items||[]).map(c=>({id:c.id,name:c.name,trade:c.trade,batchNumber})),...r.data})}
if(a==='companies-list'){const aid=account(req.query.hubId),t=await user(req),all=await companies(aid,t,req.query.status||'all'),yes=v=>String(v)==='true';let items=all;if(yes(req.query.noMembers))items=items.filter(c=>Number(c.userSize||0)===0);if(yes(req.query.noErp))items=items.filter(c=>!String(c.erpId||'').trim());if(yes(req.query.noTax))items=items.filter(c=>!String(c.taxId||'').trim());const search=String(req.query.search||'').toLowerCase();if(search)items=items.filter(c=>[c.name,c.trade,c.erpId,c.taxId].some(x=>String(x||'').toLowerCase().includes(search)));return res.json({totalAll:all.length,totalFiltered:items.length,companies:items.map(c=>({id:c.id,name:c.name,trade:c.trade,status:c.status,userSize:c.userSize,projectSize:c.projectSize,erpId:c.erpId||'',taxId:c.taxId||'',imageUrl:c.imageUrl||''}))})}
if(a==='companies-manage'){const aid=account(req.query.hubId||req.body.hubId),cid=req.query.companyId||req.body.companyId||req.body.id,t=await user(req),headers={Authorization:`Bearer ${t}`};if(req.method==='GET'){const r=await axios.get(`${APS}/hq/v1/accounts/${aid}/companies/${cid}`,{headers});return res.json({company:r.data})}if(req.body.action==='image'){const buf=Buffer.from(req.body.base64,'base64'),form=new FormData();form.append('chunk',new Blob([buf],{type:req.body.mimeType||'image/png'}),req.body.fileName||'company-image.png');const r=await fetch(`${APS}/hq/v1/accounts/${aid}/companies/${cid}/image`,{method:'PATCH',headers,body:form});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)return res.status(r.status).json({message:data.message||'Image upload failed'});return res.json({company:data})}headers['Content-Type']='application/json';let body;if(req.body.action==='purge')body={name:`removed at ${new Date().toUTCString()} ${cid}`,status:'deleted'};else{body={};for(const k of['name','trade','erp_id','tax_id'])if(req.body[k]!==undefined)body[k]=String(req.body[k]).trim()}const r=await axios.patch(`${APS}/hq/v1/accounts/${aid}/companies/${cid}`,body,{headers});return res.json({company:r.data})}
if(a==='projects'){const t=await user(req),aid=account(req.query.hubId),all=await pages(`${APS}/construction/admin/v1/accounts/${aid}/projects`,t);return res.json({projects:all.map(p=>({id:p.id,name:p.name,status:p.status,classification:p.classification||p.projectClassification||'production'}))})}
if(a==='project-users'){const t=await user(req),all=await pages(`${APS}/construction/admin/v1/projects/${req.query.projectId}/users`,t);return res.json({users:all.map(u=>({id:u.id,name:u.name,email:u.email,status:u.status,companyName:u.companyName||u.company?.name||'',roles:u.roles||[],role:u.role||''}))})}
if(a==='project-users-bulk'){const t=await user(req),ids=req.body.userIds||[],results=[];for(const id of ids){try{if(req.body.operation==='remove')await axios.delete(`${APS}/construction/admin/v1/projects/${req.body.projectId}/users/${id}`,{headers:{Authorization:`Bearer ${t}`}});else await axios.patch(`${APS}/construction/admin/v1/projects/${req.body.projectId}/users/${id}`,{role:req.body.role,roles:[req.body.role]},{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});results.push({id,success:true})}catch(e){results.push({id,success:false,error:e.response?.data?.message||e.message})}}return res.json({requested:ids.length,success:results.filter(x=>x.success).length,failed:results.filter(x=>!x.success).length,results})}
if(a==='companies-purge'){const aid=account(req.body.hubId),t=await user(req),all=await companies(aid,t,'active'),candidates=all.filter(c=>Number(c.userSize||0)===0);if(!req.body.execute)return res.json({candidates});if(req.body.confirmText!=='PURGE')return res.status(400).json({message:'Type PURGE'});const ids=new Set(req.body.companyIds||[]),selected=candidates.filter(c=>ids.has(c.id)),results=[];let patched=0,failed=0;for(const c of selected)try{const name=`removed at ${new Date().toUTCString()} ${c.id}`;await axios.patch(`${APS}/hq/v1/accounts/${aid}/companies/${c.id}`,{name,status:'deleted'},{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});patched++;results.push({id:c.id,oldName:c.name,name,success:true})}catch(e){failed++;results.push({id:c.id,name:c.name,success:false,error:e.response?.data?.message||e.message})}return res.json({requested:selected.length,patched,failed,results})}
return res.status(404).json({message:'Unknown action'})}catch(e){error(res,e)}};
