const axios=require('axios'),crypto=require('crypto');const APS='https://developer.api.autodesk.com';
function cfg(){for(const k of['APS_CLIENT_ID','APS_CLIENT_SECRET','APS_CALLBACK_URL','SESSION_SECRET'])if(!process.env[k]){const e=new Error('Missing environment variable: '+k);e.status=400;throw e}}
const basic=()=>Buffer.from(`${process.env.APS_CLIENT_ID}:${process.env.APS_CLIENT_SECRET}`).toString('base64');const key=()=>crypto.createHash('sha256').update(process.env.SESSION_SECRET).digest();
function enc(o){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),d=Buffer.concat([c.update(JSON.stringify(o)),c.final()]);return Buffer.concat([iv,c.getAuthTag(),d]).toString('base64url')}
function dec(v){try{const b=Buffer.from(v||'','base64url'),d=crypto.createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]))}catch{return null}}
function session(req){const m=(req.headers.cookie||'').match(/(?:^|; )autodesk_session=([^;]+)/);return dec(m&&m[1])}function setSession(res,v){res.setHeader('Set-Cookie',`autodesk_session=${v}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`)}
async function appToken(scope='account:read account:write'){cfg();const b=new URLSearchParams({grant_type:'client_credentials',scope}),r=await axios.post(`${APS}/authentication/v2/token`,b,{headers:{Authorization:`Basic ${basic()}`,'Content-Type':'application/x-www-form-urlencoded'}});return r.data.access_token}
async function userToken(req){const s=session(req);if(!s?.access_token){const e=new Error('Autodesk is not connected.');e.status=401;throw e}return s.access_token}
const account=h=>h?.startsWith('b.')?h.slice(2):h||'';const clean=v=>{const s=String(v??'').trim();return!s||['0','n/a','na','null','undefined','-'].includes(s.toLowerCase())?undefined:s};function fail(res,e){res.status(e.status||e.response?.status||500).json({message:e.response?.data?.developerMessage||e.response?.data?.message||e.message||'Request failed',details:e.response?.data||null})}
module.exports={axios,APS,cfg,basic,enc,session,setSession,appToken,userToken,account,clean,fail};
