const{axios,APS,account,basic,enc,session,setSession,appToken,userToken,page,fail}=require('../lib/core');
module.exports=async(req,res)=>{try{const a=String(req.query.action||'');
if(a==='auth-login'){const u=new URL(`${APS}/authentication/v2/authorize`);u.search=new URLSearchParams({response_type:'code',client_id:process.env.APS_CLIENT_ID,redirect_uri:process.env.APS_CALLBACK_URL,scope:'data:read account:read account:write'});return res.json({url:u.toString()})}
if(a==='auth-callback'){const b=new URLSearchParams({grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.APS_CALLBACK_URL}),r=await axios.post(`${APS}/authentication/v2/token`,b,{headers:{Authorization:`Basic ${basic()}`,'Content-Type':'application/x-www-form-urlencoded'}});setSession(res,enc({access_token:r.data.access_token,refresh_token:r.data.refresh_token}));return res.json({ok:true})}
if(a==='auth-status')return res.json({authenticated:!!session(req)});if(a==='auth-logout'){res.setHeader('Set-Cookie','autodesk_session=; Path=/; Max-Age=0');return res.json({ok:true})}
if(a==='hubs'){const t=await userToken(req),r=await axios.get(`${APS}/project/v1/hubs`,{headers:{Authorization:`Bearer ${t}`}});return res.json({hubs:(r.data.data||[]).map(h=>({id:h.id,name:h.attributes?.name||h.id}))})}
if(a==='projects-page'){const t=await userToken(req),offset=+req.query.offset||0,p=await page(`${APS}/construction/admin/v1/accounts/${account(req.query.hubId)}/projects`,t,200,offset);return res.json({items:p.items.map(x=>({id:x.id,name:x.name||'',jobNumber:x.jobNumber||x.job_number||'',status:x.status||'',classification:x.classification||x.projectClassification||'',type:x.type||x.projectType||'',platform:(String(x.classification||x.type||'').toLowerCase().includes('bim')?'BIM 360':'Unknown/ACC')})),total:p.total,nextOffset:offset+p.items.length,hasMore:offset+p.items.length<p.total})}
if(a==='projects-rename'){const t=await appToken('account:write'),aid=account(req.body.hubId),results=[];for(const p of req.body.projects||[]){const pid=account(p.id);try{const body={name:p.proposedName};if(p.proposedJobNumber!==undefined)body.job_number=p.proposedJobNumber;const r=await axios.patch(`${APS}/hq/v1/accounts/${aid}/projects/${pid}`,body,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});results.push({...p,success:true,response:r.data})}catch(e){const status=e.response?.status||500,raw=e.response?.data?.developerMessage||e.response?.data?.message||e.message;results.push({...p,success:false,unsupported:[400,404,409,422].includes(status),error:raw,statusCode:status})}}return res.json({results})}
if(a==='companies-page'){const t=await userToken(req),aid=account(req.query.hubId),offset=+req.query.offset||0,p=await page(`${APS}/construction/admin/v1/accounts/${aid}/companies?filter%5Bstatus%5D=all&sort=name`,t,200,offset);return res.json({items:p.items.map(c=>({id:c.id,name:c.name,trade:c.trade||'',erpId:c.erpId||'',taxId:c.taxId||'',members:c.userSize||0,projects:c.projectSize||0,status:c.status||''})),total:p.total,nextOffset:offset+p.items.length,hasMore:offset+p.items.length<p.total})}
if(a==='hub-users-page'){const t=await appToken('account:read'),aid=account(req.query.hubId),offset=+req.query.offset||0,p=await page(`${APS}/hq/v1/accounts/${aid}/users`,t,100,offset);return res.json({items:p.items.map(u=>({id:u.id,name:u.name||`${u.first_name||''} ${u.last_name||''}`.trim(),email:u.email||'',company:u.company_name||u.companyName||'',companyId:u.company_id||u.companyId||'',status:u.status||''})),total:p.total,nextOffset:offset+p.items.length,hasMore:offset+p.items.length<p.total})}
if(a==='selected-project-users'){const t=await userToken(req),items=[];for(const pr of req.body.projects||[]){for(let o=0,total=1;o<total;o+=100){const p=await page(`${APS}/construction/admin/v1/projects/${pr.id}/users`,t,100,o);items.push(...p.items.map(u=>({key:`${pr.id}::${u.id}`,projectId:pr.id,projectName:pr.name,userId:u.id,name:u.name,email:u.email,company:u.companyName||u.company?.name||'',roles:u.roles||[],status:u.status||''})));total=p.total}}return res.json({items})}
if(a==='members-remove'){const t=await userToken(req),results=[];for(const m of req.body.items||[])try{await axios.delete(`${APS}/construction/admin/v1/projects/${m.projectId}/users/${m.userId}`,{headers:{Authorization:`Bearer ${t}`}});results.push({...m,success:true})}catch(e){results.push({...m,success:false,error:e.response?.data?.message||e.message})}return res.json({results})}
if(a==='bulk-user-company'){const t=await appToken('account:write'),aid=account(req.body.hubId),results=[];for(const u of req.body.users||[])try{await axios.patch(`${APS}/hq/v1/accounts/${aid}/users/${u.id}`,{company_id:req.body.companyId},{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});results.push({...u,success:true})}catch(e){results.push({...u,success:false,error:e.response?.data?.message||e.message})}return res.json({results})}
return res.status(404).json({message:'Unknown action'})}catch(e){fail(res,e)}};
