const{axios,APS,cfg,basic,enc,session,cookie,appToken,userToken,account,companyPayload,error}=require('../lib/_lib');
async function pages(url,t){let all=[],offset=0,total=1;while(offset<total){const join=url.includes('?')?'&':'?';const r=await axios.get(`${url}${join}limit=200&offset=${offset}`,{headers:{Authorization:`Bearer ${t}`}});const batch=r.data.results||[];all.push(...batch);total=r.data.pagination?.totalResults||all.length;offset+=r.data.pagination?.limit||200;if(!batch.length)break}return all}
async function companies(aid,t,status='all'){return pages(`${APS}/construction/admin/v1/accounts/${aid}/companies?filter%5Bstatus%5D=${encodeURIComponent(status)}&sort=name`,t)}
module.exports=async(req,res)=>{try{const a=String(req.query.action||'');
if(a==='auth-login'){cfg();const u=new URL(`${APS}/authentication/v2/authorize`);u.search=new URLSearchParams({response_type:'code',client_id:process.env.APS_CLIENT_ID,redirect_uri:process.env.APS_CALLBACK_URL,scope:'data:read account:read account:write'});return res.json({url:u.toString()})}
if(a==='auth-callback'){const b=new URLSearchParams({grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.APS_CALLBACK_URL}),r=await axios.post(`${APS}/authentication/v2/token`,b,{headers:{Authorization:`Basic ${basic()}`,'Content-Type':'application/x-www-form-urlencoded'}});cookie(res,enc({access_token:r.data.access_token,refresh_token:r.data.refresh_token}));return res.json({ok:true})}
if(a==='auth-status')return res.json({authenticated:!!session(req)});
if(a==='auth-logout'){res.setHeader('Set-Cookie','autodesk_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return res.json({authenticated:false})}
if(a==='hubs'){const t=await userToken(req),r=await axios.get(`${APS}/project/v1/hubs`,{headers:{Authorization:`Bearer ${t}`}});return res.json({hubs:(r.data.data||[]).map(h=>({id:h.id,name:h.attributes?.name||h.id,accountId:account(h.id)}))})}
if(a==='companies-existing'){const t=await userToken(req),all=await companies(account(req.query.hubId),t,'active');return res.json({companies:all.map(c=>({id:c.id,name:c.name}))})}
if(a==='companies-import'){const aid=account(req.body.hubId),items=(req.body.companies||[]).map(companyPayload).filter(Boolean).slice(0,50),t=await appToken('account:write'),r=await axios.post(`${APS}/hq/v1/accounts/${aid}/companies/import`,items,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});return res.json({...r.data,added:(r.data.success_items||[]).map(c=>({id:c.id,name:c.name,trade:c.trade,batch:req.body.batch}))})}
if(a==='companies-list'){const t=await userToken(req),aid=account(req.query.hubId),limit=Math.min(Number(req.query.limit||200),200),offset=Math.max(Number(req.query.offset||0),0),status=req.query.status||'all',p=new URLSearchParams({limit:String(limit),offset:String(offset),'filter[status]':status,sort:'name'});const r=await axios.get(`${APS}/construction/admin/v1/accounts/${aid}/companies?${p}`,{headers:{Authorization:`Bearer ${t}`}}),batch=r.data.results||[],total=r.data.pagination?.totalResults||batch.length;return res.json({offset,limit,total,nextOffset:offset+batch.length,hasMore:offset+batch.length<total,companies:batch.map(c=>({id:c.id,name:c.name,trade:c.trade||'',erpId:c.erpId||'',taxId:c.taxId||'',status:c.status||'',members:c.userSize||0,projects:c.projectSize||0,imageUrl:c.imageUrl||''}))})}
if(a==='company-projects'){const t=await userToken(req),aid=account(req.query.hubId),companyId=req.query.companyId,detail=await axios.get(`${APS}/hq/v1/accounts/${aid}/companies/${companyId}`,{headers:{Authorization:`Bearer ${t}`}}),d=detail.data||{},embedded=d.projects||d.project_associations||d.projectAssociations||[];if(embedded.length)return res.json({company:{id:companyId,name:d.name},projects:embedded.map(p=>({id:p.id||p.project_id||p.projectId,name:p.name||p.project_name||p.projectName||p.id,status:p.status||'',members:p.member_count||p.memberCount||p.userSize||0,activeMembers:p.member_count||p.memberCount||p.userSize||0,deletedMembers:0,companyStatus:d.status||'',companyDeleted:String(d.status||'').toLowerCase()==='deleted',source:'company-detail'})),complete:true});const projects=await pages(`${APS}/construction/admin/v1/accounts/${aid}/projects`,t),matches=[];for(const project of projects){let offset=0,total=1,members=[];while(offset<total){try{const r=await axios.get(`${APS}/construction/admin/v1/projects/${project.id}/users?limit=200&offset=${offset}`,{headers:{Authorization:`Bearer ${t}`}}),batch=r.data.results||[];for(const u of batch){const uc=u.company||{},uid=u.companyId||u.company_id||uc.id;if(String(uid||'')===String(companyId))members.push({id:u.id,name:u.name,email:u.email,roles:u.roles||[],status:u.status||'',deleted:String(u.status||'').toLowerCase()==='deleted'||String(u.status||'').toLowerCase()==='inactive',companyId:uid})}total=r.data.pagination?.totalResults||batch.length;offset+=r.data.pagination?.limit||200;if(!batch.length)break}catch(e){break}}if(members.length)matches.push({id:project.id,name:project.name,status:project.status||'',classification:project.classification||project.projectClassification||'',members:members.length,activeMembers:members.filter(m=>!m.deleted).length,deletedMembers:members.filter(m=>m.deleted).length,memberList:members,companyStatus:d.status||'',companyDeleted:String(d.status||'').toLowerCase()==='deleted',source:'membership-scan'})}return res.json({company:{id:companyId,name:d.name},projects:matches,complete:true})}
if(a==='company-update'){const t=await userToken(req),aid=account(req.body.hubId),headers={Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body={};for(const k of['name','trade','erp_id','tax_id'])if(req.body[k]!==undefined)body[k]=String(req.body[k]).trim();const r=await axios.patch(`${APS}/hq/v1/accounts/${aid}/companies/${req.body.companyId}`,body,{headers});return res.json({company:r.data})}
if(a==='company-image'){const t=await userToken(req),aid=account(req.body.hubId),buf=Buffer.from(req.body.base64,'base64'),form=new FormData();form.append('chunk',new Blob([buf],{type:req.body.mimeType||'image/png'}),req.body.fileName||'company.png');const r=await fetch(`${APS}/hq/v1/accounts/${aid}/companies/${req.body.companyId}/image`,{method:'PATCH',headers:{Authorization:`Bearer ${t}`},body:form});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)return res.status(r.status).json({message:data.message||'Image upload failed'});return res.json({company:data})}
if(a==='companies-purge'){const t=await userToken(req),aid=account(req.body.hubId),all=await companies(aid,t,'active'),ids=new Set(req.body.companyIds||[]),selected=all.filter(c=>ids.has(c.id)&&Number(c.userSize||0)===0),results=[];if(req.body.confirmText!=='PURGE')return res.status(400).json({message:'Type PURGE'});for(const c of selected)try{const name=`removed at ${new Date().toUTCString()} ${c.id}`;await axios.patch(`${APS}/hq/v1/accounts/${aid}/companies/${c.id}`,{name,status:'deleted'},{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});results.push({id:c.id,oldName:c.name,newName:name,success:true})}catch(e){results.push({id:c.id,oldName:c.name,success:false,error:e.response?.data?.message||e.message})}return res.json({requested:selected.length,success:results.filter(x=>x.success).length,failed:results.filter(x=>!x.success).length,results})}
if(a==='projects'){const t=await userToken(req),all=await pages(`${APS}/construction/admin/v1/accounts/${account(req.query.hubId)}/projects`,t);return res.json({projects:all.map(p=>({id:p.id,name:p.name,status:p.status,classification:p.classification||p.projectClassification||'production'}))})}
if(a==='memberships'){const t=await userToken(req),projectId=req.body.projectId,limit=Math.min(Number(req.body.limit||200),200),offset=Math.max(Number(req.body.offset||0),0),pr=await axios.get(`${APS}/construction/admin/v1/projects/${projectId}`,{headers:{Authorization:`Bearer ${t}`}}).catch(()=>({data:{name:projectId}})),r=await axios.get(`${APS}/construction/admin/v1/projects/${projectId}/users?limit=${limit}&offset=${offset}`,{headers:{Authorization:`Bearer ${t}`}}),batch=r.data.results||[],total=r.data.pagination?.totalResults||batch.length;return res.json({projectId,projectName:pr.data.name||projectId,offset,limit,total,nextOffset:offset+batch.length,hasMore:offset+batch.length<total,memberships:batch.map(u=>({key:`${projectId}::${u.id}`,projectId,projectName:pr.data.name||projectId,userId:u.id,name:u.name,email:u.email,company:u.companyName||u.company?.name||'',roles:u.roles||[],status:u.status||'active'}))})}
if(a==='memberships-bulk'){const t=await userToken(req),results=[];for(const m of(req.body.memberships||[]))try{if(req.body.operation==='remove')await axios.delete(`${APS}/construction/admin/v1/projects/${m.projectId}/users/${m.userId}`,{headers:{Authorization:`Bearer ${t}`}});else await axios.patch(`${APS}/construction/admin/v1/projects/${m.projectId}/users/${m.userId}`,{role:req.body.role,roles:[req.body.role]},{headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});results.push({...m,success:true})}catch(e){results.push({...m,success:false,error:e.response?.data?.message||e.message})}return res.json({requested:results.length,success:results.filter(x=>x.success).length,failed:results.filter(x=>!x.success).length,results})}
return res.status(404).json({message:'Unknown API action'})}catch(e){error(res,e)}};
